# Generated by Django 5.2.12 on 2026-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                ("role", models.CharField(max_length=200, verbose_name="Cargo")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="Foto"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Integrante del equipo",
                "verbose_name_plural": "Equipo",
                "ordering": ["order"],
            },
        ),
    ]
