# Generated by Django 5.2.12 on 2026-08-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Porcentaje"), ("fixed", "Monto fijo")],
                        max_length=10,
                        verbose_name="Tipo de descuento",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor del descuento",
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monto mínimo de compra",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Válido desde"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Válido hasta"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = ilimitado",
                        verbose_name="Usos máximos",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usos realizados"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
                "ordering": ["-created_at"],
            },
        ),
    ]
