# Generated by Django 5.2.12 on 2026-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dejá vacío si no tiene descuento",
                max_digits=10,
                null=True,
                verbose_name="Precio de oferta",
            ),
        ),
    ]
