# Generated by Django 5.2.12 on 2026-03-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_product_discount_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="Imagen"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen del producto",
                "verbose_name_plural": "Imágenes del producto",
                "ordering": ["order"],
            },
        ),
    ]
