# Generated by Django 5.2.12 on 2026-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="verified_purchase",
            field=models.BooleanField(default=False, verbose_name="Compra verificada"),
        ),
    ]
