# Generated by Django 5.2.12 on 2026-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        max_digits=10,
                        verbose_name="Envío gratis desde ($)",
                    ),
                ),
                (
                    "pickup_address",
                    models.CharField(
                        default="Av. Corrientes 1234, CABA, Buenos Aires",
                        max_length=250,
                        verbose_name="Dirección de retiro",
                    ),
                ),
                (
                    "pickup_hours",
                    models.CharField(
                        default="Lunes a Viernes 8:00 - 18:00, Sábados 9:00 - 14:00",
                        max_length=250,
                        verbose_name="Horarios de retiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de envío",
                "verbose_name_plural": "Configuración de envío",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Retiro en local"),
                            ("standard", "Envío estándar"),
                            ("express", "Envío express"),
                            ("andreani", "Andreani"),
                            ("oca", "OCA"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Descripción"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Método de envío",
                "verbose_name_plural": "Métodos de envío",
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio base"
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Precio por kg",
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveIntegerField(default=1, verbose_name="Días mín."),
                ),
                (
                    "estimated_days_max",
                    models.PositiveIntegerField(default=3, verbose_name="Días máx."),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Zona de envío",
                "verbose_name_plural": "Zonas de envío",
                "ordering": ["base_price"],
            },
        ),
    ]
