# Generated by Django 5.2.12 on 2026-03-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_shipping_method_order_shipping_price_and_more"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "tracking_url",
                    models.CharField(
                        blank=True,
                        help_text="Usá {tracking_number} como placeholder. Ej: https://www.andreani.com/#!/informacionEnvio/{tracking_number}",
                        max_length=500,
                        verbose_name="URL de seguimiento",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Transportista",
                "verbose_name_plural": "Transportistas",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de seguimiento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparando envío"),
                            ("picked_up", "Retirado por transportista"),
                            ("in_transit", "En camino"),
                            ("out_for_delivery", "En reparto"),
                            ("delivered", "Entregado"),
                            ("failed", "Entrega fallida"),
                            ("returned", "Devuelto"),
                        ],
                        default="preparing",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateField(
                        blank=True, null=True, verbose_name="Entrega estimada"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de entrega"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas internas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipping.carrier",
                        verbose_name="Transportista",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparando envío"),
                            ("picked_up", "Retirado por transportista"),
                            ("in_transit", "En camino"),
                            ("out_for_delivery", "En reparto"),
                            ("delivered", "Entregado"),
                            ("failed", "Entrega fallida"),
                            ("returned", "Devuelto"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipping.shipment",
                        verbose_name="Envío",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento del envío",
                "verbose_name_plural": "Eventos del envío",
                "ordering": ["-created_at"],
            },
        ),
    ]
