# Generated by Django 5.2.12 on 2026-03-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingmethod",
                verbose_name="Método de envío",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Costo de envío",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.shippingzone",
                verbose_name="Zona de envío",
            ),
        ),
    ]
