# Generated by Django 5.2.12 on 2026-03-15 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_shipping_method_order_shipping_price_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Transportista"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateField(
                blank=True, null=True, verbose_name="Entrega estimada"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("failed", "Rechazado"),
                    ("refunded", "Reembolsado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado del pago",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Número de seguimiento"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(blank=True, verbose_name="URL de seguimiento"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de pago"),
                    ("paid", "Pagado"),
                    ("preparing", "En preparación"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado del pedido",
            ),
        ),
        migrations.CreateModel(
            name="OrderTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("question", "Consulta"),
                            ("claim", "Reclamo"),
                            ("return", "Devolución"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Asunto")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("in_progress", "En proceso"),
                            ("resolved", "Resuelto"),
                            ("closed", "Cerrado"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, verbose_name="Respuesta"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-created_at"],
            },
        ),
    ]
