# Generated by Django 5.2.12 on 2026-03-15 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_carrier_name_order_estimated_delivery_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="carrier_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="estimated_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tracking_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tracking_url",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "No pagado"),
                    ("paid", "Pagado"),
                    ("refunded", "Reembolsado"),
                    ("failed", "Fallido"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Estado de pago",
            ),
        ),
        migrations.CreateModel(
            name="OrderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("question", "Consulta"),
                            ("complaint", "Reclamo"),
                            ("suggestion", "Sugerencia"),
                            ("other", "Otro"),
                        ],
                        default="question",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Asunto")),
                ("body", models.TextField(verbose_name="Mensaje")),
                (
                    "is_from_staff",
                    models.BooleanField(
                        default=False, verbose_name="Respuesta del vendedor"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leído")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje del pedido",
                "verbose_name_plural": "Mensajes del pedido",
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="OrderTicket",
        ),
    ]
