# Generated by Django 5.2.12 on 2026-08-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_coupon_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_restored",
            field=models.BooleanField(default=False, verbose_name="Stock repuesto"),
        ),
    ]
